name: amworkflow
channels:
  - conda-forge
  - defaults
dependencies:
  - pythonocc-core=7.7.0
  - python=3.10
  - pandas
  - sqlite
  - numpy
  - fenics-dolfinx
  - mpich
  - pyvista
  - doit
  - tomlkit
  - pip
  - pip:
    - gmsh==4.11.1
    - networkx
    - pyqt5
    - sphinx
    - sqlalchemy
    - ruamel-yaml
    - doit
    - psutil
    - flatdict
